version: "3.0"

networks:
  docker_registry_network:


services:
  nginx_gateway_services:
    image: nginx:1.23.2
    container_name: registry_gateway_container
    restart: always
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
    ports:
      - 5480:80
      - 54443:443
    networks:
      - docker_registry_network

  docker_registry_services:
    container_name: docker_registry_container
    image: registry:2
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io/
    volumes:
      - ./auth:/auth
      - ./data/registry:/var/lib/registry
    networks:
      - docker_registry_network

  docker_registry_gui:
    container_name: docker_registry_gui_container
    image: joxit/docker-registry-ui
    restart: always
    environment:
      - REGISTRY_TITLE=private_dockerhub
    networks:
      - docker_registry_network
