version: "3.0"

networks:
  docker_registry:


services:
  nginx_gateway_services:
    image: nginx:1.23.2
    container_name: registry_gateway_container
    restart: always
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
    ports:
      - 34800:34800
    links:
      - docker_registry_services
      - docker_registry_gui
    networks:
      - docker_registry

  docker_registry_services:
    user: root
    container_name: docker_registry_container
    image: registry:2
    restart: always
    ports:
      - 34500:34500
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:34500
    volumes:
      - ./conf/registry:/etc/docker/registry
      - ./data/registry:/var/lib/registry
    networks:
      - docker_registry

  docker_registry_gui:
    user: root
    container_name: docker_registry_gui_container
    image: joxit/docker-registry-ui
    restart: always
    environment:
      - REGISTRY_TITLE=shicheng.yu-private-dockerhub
    networks:
      - docker_registry
