version: "3.0"

networks:
  docker_registry:


services:
  docker_registry_services:
    user: root
    container_name: docker_registry_container
    image: registry:2
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:34500
    ports:
      - 34500:34500
    volumes:
      - ./conf:/etc/docker/registry
      - ./data/registry:/var/lib/registry
    networks:
      - docker_registry

  docker_registry_gui:
    user: root
    container_name: docker_registry_gui_container
    image: joxit/docker-registry-ui
    restart: always
    ports:
      - 34800:80
    environment:
      - REGISTRY_TITLE=shicheng.yu-private-dockerhub
      - REGISTRY_URL=http://localhost:34500
    networks:
      - docker_registry
